<a href="https://colab.research.google.com/github/divyatalera/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

NumPy is a Python library used for working with arrays.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.


In [61]:
#creating array using numpy
import numpy as np

arr1 = np.array(['a', 'b', 'c', 4, 5])   #1D array
arr2 = np.array([['d', 'e', 3], ['x', 's', 6]])   #2D array
arr3 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])  #3D array

print(arr1)
print(arr2)
print(arr3)

print(type(arr1))

arr4 = np.array(['m', 'a', 'n', 4], ndmin=6)

print(arr4)
print('number of dimensions :', arr4.ndim)

['a' 'b' 'c' '4' '5']
[['d' 'e' '3']
 ['x' 's' '6']]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[[[[['m' 'a' 'n' '4']]]]]]
number of dimensions : 6


In [62]:
#Array Indexing using numpy

arr = np.array([1, 2, 5, 4])
print(arr[1])
print(arr[1] + arr[3])

arr1 = np.array([[1,2,4,5], [6,7,8,9]])
print('2nd element on 1st dim: ', arr1[0, 1])
print('4th element on 2nd dim: ', arr1[1, 3])
print('Last element from 2nd dim: ', arr1[1, -1])

arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr2[1, 0, 1])

2
6
2nd element on 1st dim:  2
4th element on 2nd dim:  9
Last element from 2nd dim:  9
8


In [63]:
#Array Slicing

arr = np.array(['a', 'b', 'c', 4, 5, 6, 7])

print(arr[1:5]) #print array[start:end]
#Note: The result includes the start index but not the end.

print(arr[4:]) 
#Note: The result includes 4th index till end of the array

print(arr[:4])
#Note: the result includes all the elements from start till 4th index

print(arr[-3:-1])
#Note: the array is numbered as [-7,-6,-5,-4,-3,-2,-1]

print(arr[1:5:2])
# Note: the result includes [start,end,step]
# step is jump it takes from one element to other
# here it is 2

arr = np.array([['a','b','c','d','e'], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) #from second set slice 1 to 4
print(arr[0:2, 3]) #from both set get 4th element
print(arr[0:2, 1:4]) #from both set slice 1 to 4




['b' 'c' '4' '5']
['5' '6' '7']
['a' 'b' 'c' '4']
['5' '6']
['b' '4']
['7' '8' '9']
['d' '9']
[['b' 'c' 'd']
 ['7' '8' '9']]


In [64]:
#Array Datatypes in numpy
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr1 = np.array(['charger', 'battery', 'samsung'])
print(arr1.dtype) 

arr2 = np.array([1, 2, 3, 4], dtype='S')
print(arr2)

arr3 = np.array([1.1, 2.1, 3.1])
arr4 = arr3.astype(int) #converts into integer
print(arr4)
print(arr4.dtype)

int64
<U7
[b'1' b'2' b'3' b'4']
[1 2 3]
int64


In [65]:
# Numpy Array shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
#the result includes (2, 4), which means that the array has 2 dimensions
#and each dimension has 4 elements.


(2, 4)


In [66]:
#NumPy Array Reshaping

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

#convert 1D to 2D array
newarr = arr.reshape(4, 3) 
#The outermost dimension will have 4 arrays, each with 3 elements:

#convert 1D to 3D array
newarr1 = arr.reshape(2, 3, 2)
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

print(newarr)
print(newarr1)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [67]:
#Numpy Array iterating

#Iterate on the elements of 1-D array
arr = np.array(['apple','mango','cherry'])
for x in arr:
  print(x)

#Iterate on the elements of 2-D array
arr1 = np.array([[1, 2, 3], ['cat','ball','bat']])
for x in arr1:
    print(x)

#to Iterate each element of 2D-array
arr2 = np.array([[1, 2, 3], ['cat','ball','bat']])
for x in arr2:
  for y in x: 
    print(y)


#Iterate on the elements of 3-D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr3:
  print(x)

#to Iterate each element of 3D-array
arr4 = np.array([[['cat','ball','bat'], [4, 5, 6]], [['apple','mango','cherry'], [10, 11, 12]]])
for x in arr4:
  for y in x:
    for z in y: 
      print(z)
 

apple
mango
cherry
['1' '2' '3']
['cat' 'ball' 'bat']
1
2
3
cat
ball
bat
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
cat
ball
bat
4
5
6
apple
mango
cherry
10
11
12


In [68]:
#Joining Numpy Array
#Joining 1D-aray
arr1 = np.array([1, 2, 3])
arr2 = np.array(['a','b','c'])

#concatention method
arr = np.concatenate((arr1, arr2))
print(arr)

#stacking method
arr6 = np.stack((arr1, arr2), axis=1)  #stacking along axis
arr7 = np.hstack((arr1, arr2))  #row stacking
arr8 = np.vstack((arr1, arr2))  #column stacking
arr9 = np.dstack((arr1, arr2))  #column stacking

print(arr6)
print(arr7)
print(arr8)
print(arr9)

#Joining 2D-aray
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
arr5 = np.concatenate((arr3, arr4), axis=1) #axis 0=down, axis 1=across
print(arr5)


['1' '2' '3' 'a' 'b' 'c']
[['1' 'a']
 ['2' 'b']
 ['3' 'c']]
['1' '2' '3' 'a' 'b' 'c']
[['1' '2' '3']
 ['a' 'b' 'c']]
[[['1' 'a']
  ['2' 'b']
  ['3' 'c']]]
[[1 2 5 6]
 [3 4 7 8]]


In [69]:
#Spliting Numpy Array

# Splitting 1-D Arrays

arr = np.array(['bat','ball','cat','mat','apple',4,7,12,34])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[2]) #you can access any array separately using this

#Splitting 2-D Arrays
arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr1 = np.array_split(arr1, 4) #splitting 2d-array into 4 arrays.
print(newarr1)

#hsplit(), vsplit() and dsplit() can be used to split
#row, column and depth wise.


[array(['bat', 'ball', 'cat'], dtype='<U5'), array(['mat', 'apple', '4'], dtype='<U5'), array(['7', '12', '34'], dtype='<U5')]
['7' '12' '34']
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [70]:
#Searching Arrays using Numpy

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4) #find a specific number
x1 = np.where(arr%2 == 0)  #find all even number
x2 = np.where(arr%2 == 1)  #find all odd number

print(x)
print(x1)
print(x2)
#Note: the result will be the index of the element

(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)


**Search Sorted**

*There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.*


In [71]:
array = np.array([1, 7, 5, 9])
x = np.searchsorted(array, 5)
x1 = np.searchsorted(array, 5, side='right')
x2 = np.searchsorted(array, 5, side='left')

print(x)
print(x1)
print(x2)


1
3
1


In [72]:
#Sorting array

#Sorting 1D-array
arr = np.array([67, 34, 70, 41])
print(np.sort(arr))

#sorting array alphabetically
arr1 = np.array(['vivo','samsung','oppo','appple'])
print(np.sort(arr1))

#Sorting 2D-array
arr2 = np.array([[33, 12, 74], ['vivo','samsung','oppo']])
print(np.sort(arr2))

[34 41 67 70]
['appple' 'oppo' 'samsung' 'vivo']
[['12' '33' '74']
 ['oppo' 'samsung' 'vivo']]
