In [8]:
#creating array using numpy
import numpy as np

arr1 = np.array(['a', 'b', 'c', 4, 5])   #1D array
arr2 = np.array([['d', 'e', 3], ['x', 's', 6]])   #2D array
arr3 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])  #3D array

print(arr1)
print(arr2)
print(arr3)

print(type(arr1))

arr4 = np.array(['m', 'a', 'n', 4], ndmin=6)

print(arr4)
print('number of dimensions :', arr4.ndim)

['a' 'b' 'c' '4' '5']
[['d' 'e' '3']
 ['x' 's' '6']]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[[[[['m' 'a' 'n' '4']]]]]]
number of dimensions : 6
